export const ON_SQUARE_ACTIVATE    = 'ON_SQUARE_ACTIVATE';
export const ON_SQUARE_DEACTIVATE  = 'ON_SQUARE_DEACTIVATE';
export const ON_BLAST              = 'ON_BLAST';
export const ON_GAME_RESET         = 'ON_GAME_RESET';
export const ON_LEVEL_DONE         = 'ON_LEVEL_DONE'
export const ON_NEXT_LEVEL         = 'ON_NEXT_LEVEL'
export const ON_PREV_LEVEL         = 'ON_PREV_LEVEL'
export const ON_RESTART_LEVEL      = 'ON_RESTART_LEVEL'

export const DEVICE_FORM_FACTOR_SET   = 'DEVICE_FORM_FACTOR_SET';
export const DEVICE_USER_AGENT_SET    = 'DEVICE_USER_AGENT_SET';
export const DEVICE_DIMENSIONS_SET    = 'DEVICE_DIMENSIONS_SET';

export const ON_ADD_TO_SHOULD_BLAST = 'ON_ADD_TO_SHOULD_BLAST';

export default {
    ON_SQUARE_ACTIVATE,
    ON_SQUARE_DEACTIVATE,
    ON_BLAST,
    ON_GAME_RESET,
    ON_LEVEL_DONE,
    ON_NEXT_LEVEL,
    ON_PREV_LEVEL,
    ON_RESTART_LEVEL,
    DEVICE_FORM_FACTOR_SET,
    DEVICE_USER_AGENT_SET,
    DEVICE_DIMENSIONS_SET,
    ON_ADD_TO_SHOULD_BLAST,
}
